build:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - wp43s
  tags:
    - macos

# run tests using the binary built before
#test:
#  stage: test
#  script:
#    - ./runmytests.sh
