stages:
  - build
  - test
  - upload
  - release

variables:
  OM_PACKAGE: "Owner_wp_43s_0_18s.pdf"
  RM_PACKAGE: "Reference_wp_43s_0_18s.pdf"
  DM42_PACKAGE: "dm42firmware.zip"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/wp43s/${CI_COMMIT_TAG}"

macOS:
  stage: build
  script:
    - make rebuild
  tags:
    - macos

linux:
  stage: build
  script:
    - apt-get update -qq
    - apt-get install -qq -y libgtk-3-dev 
    - make rebuild
  tags:
    - linux

windows:
  stage: build
  script:
    - C:\git-sdk-64\msys2_shell.cmd -defterm -mingw64 -no-start -c "make rebuild"
  tags:
    - wp43s_windows

dm42:
  stage: build
  script:
    - cd DMCP_build
    - ./build_GMP_static_ARM_library
    - ./build_WP43S.pgm_for_DM42_hardware
    - cd ..
    - mkdir DM42Firmware
    - cp DMCP_build/build/WP43S.pgm DMCP_build/build/WP43S_qspi.bin DM42Firmware
    - zip -r dm42firmware.zip DM42Firmware
  artifacts:
    expire_in: 1 day
    paths:
      - dm42firmware.zip
  tags:
    - dm42

testSuite:
  stage: test
  script:
    - apt-get update -qq
    - apt-get install -qq -y libgtk-3-dev 
    - make mrproper
    - make testSuite
    - ./testSuite
  tags:
    - linux

upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file draft\ documentation/${OM_PACKAGE} ${PACKAGE_REGISTRY_URL}/${OM_PACKAGE}
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file draft\ documentation/${RM_PACKAGE} ${PACKAGE_REGISTRY_URL}/${RM_PACKAGE}
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ${DM42_PACKAGE} ${PACKAGE_REGISTRY_URL}/${DM42_PACKAGE}
  tags:
    - linux

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"Owner's Manual\",\"url\":\"${PACKAGE_REGISTRY_URL}/${OM_PACKAGE}\"}" \
        --assets-link "{\"name\":\"Reference Manual\",\"url\":\"${PACKAGE_REGISTRY_URL}/${RM_PACKAGE}\"}" \
        --assets-link "{\"name\":\"DM42 Firmware\",\"url\":\"${PACKAGE_REGISTRY_URL}/${DM42_PACKAGE}\"}"
  tags:
    - linux
