macOS:
  stage: build
  script:
    - make mrproper
    - make
  artifacts:
    paths:
      - wp43s
  tags:
    - macos

dm42:
  stage: build
  script:
    - cd DMCP_build
    - ./build_GMP_static_ARM_library
    - ./build_WP43S.pgm_for_DM42_hardware
  artifacts:
    paths:
      - DMCP_build/build/WP43S.pgm
  tags:
    - dm42

windows:
  stage: build
  script:
    - export shell="cmd.exe //C RefreshEnv.cmd & C:/tools/msys64/msys2_shell.cmd -defterm -mingw64 -no-start -full-path -here -c \$\* --"
    - $shell make
  tags:
    - windows

testSuite:
  stage: test
  script:
    - make mrproper
    - make testSuite
    - ./testSuite
  tags:
    - testSuite
